args:
  latent_channels: 16
  mode: inference
  # load: "/root/projects/CogVideo/sat/CogVideoX-2b-sat/transformer" # This is default! "{your_CogVideoX-2b-sat_path}/transformer" This is for Full model without lora adapter
  load: /root/projects/CogVideo/sat/checkpoints/5b-lora/KevinS07-iters_20000-09-19-19-14 # /root/projects/CogVideo/sat/checkpoints/5b-lora/KevinS07-09-18-03-59 # "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter

  batch_size: 1
  input_type: txt
  input_file: configs/KevinS07.txt                         # yc: Change this!
  sampling_num_frames: 13  # Must be 13, 11 or 9
  sampling_fps: 8
  # fp16: True # For CogVideoX-2B
  bf16: True # For CogVideoX-5B
  output_dir: outputs/5b-lora/S07/KevinS07-iters_20000-09-19-19-14      # yc: Change this!
  force_inference: True